# Generated by Django 5.2 on 2025-12-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ia_active',
            new_name='is_active',
        ),
    ]
