# Generated by Django 5.2 on 2026-01-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_post',
            field=models.IntegerField(default=0),
        ),
    ]
